### ISSUE TITLE
ubantu 20.04折腾了一天都没运行起来

### ISSUE THREAD

**Issue by yangmoling** [dqzg12300/fridaUiTools#16]
源码报错如下
➜  fridaUiTools-1.0.3 ./kmainForm.py
  File "./kmainForm.py", line 339
    res = self.spawnAttachForm.exec()
                                  ^
SyntaxError: invalid syntax

打包的
yangmoling-pc% ./fridaUiTools 
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod04_ctypes.py", line 53, in __init__
  File "ctypes/__init__.py", line 373, in __init__
OSError: libcapstone.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "kmainForm.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "forms/Patch.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "utils/AsmUtil.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "capstone/__init__.py", line 312, in <module>
  File "capstone/__init__.py", line 285, in _load_lib
  File "ctypes/__init__.py", line 451, in LoadLibrary
  File "PyInstaller/loader/pyimod04_ctypes.py", line 55, in __init__
pyimod04_ctypes.PyInstallerImportError: Failed to load dynlib/dll 'libcapstone.so'. Most likely this dynlib/dll was not found when the application was frozen.
[2061672] Failed to execute script 'kmainForm' due to unhandled exception!

**Comment by dqzg12300** [comment]
如果无法运行,请将libcapstone.so复制到/usr/local/lib中

**Comment by yangmoling** [comment]
File "PyInstaller/loader/pyimod04_ctypes.py", line 55, in __init__
pyimod04_ctypes.PyInstallerImportError: Failed to load dynlib/dll 'libcapstone.so'. Most likely this dynlib/dll was not found when the application was frozen.
[2833074] Failed to execute script 'kmainForm' due to unhandled exception!

放了 依旧同样问题

**Comment by yangmoling** [comment]
解决了 放/usr/lib 中~~~~哭死
