### ISSUE TITLE
mac下无法使用

### ISSUE THREAD

**Issue by wulliwui** [dqzg12300/fridaUiTools#41]
Last login: Wed Dec 14 16:23:59 on ttys002
/Users/mac/Downloads/fridaUiTools_for_mac/kmainForm_14 ; exit;
macdeiMac-4:~ mac$ /Users/mac/Downloads/fridaUiTools_for_mac/kmainForm_14 ; exit;
Traceback (most recent call last):
  File "kmainForm.py", line 22, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "forms/Patch.py", line 6, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "utils/AsmUtil.py", line 1, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "capstone/__init__.py", line 315, in <module>
ImportError: ERROR: fail to load the dynamic library.
[2538] Failed to execute script 'kmainForm' due to unhandled exception: ERROR: fail to load the dynamic library.
[2538] Traceback:
Traceback (most recent call last):
  File "kmainForm.py", line 22, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "forms/Patch.py", line 6, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "utils/AsmUtil.py", line 1, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "capstone/__init__.py", line 315, in <module>
ImportError: ERROR: fail to load the dynamic library.

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

**Comment by dqzg12300** [comment]
`cd /Users/mac/Downloads/fridaUiTools_for_mac && ./kmainForm_14`
试试看。

**Comment by TimeBeneficiary** [comment]
> 

我是真的服气，我都产生了疑问，到底是作者离谱还是我太菜，一个开源的软件，我在 issue 里面才找到了使用方法

**Comment by dqzg12300** [comment]
哈哈。我平时都是pycharm启动的。细节没处理。
