### ISSUE TITLE
frida过检测功能闪退

### ISSUE THREAD

**Issue by CHINA-china** [dqzg12300/fridaUiTools#61]
frida过检测功能闪退
![image](https://github.com/dqzg12300/fridaUiTools/assets/92798047/e087edff-356a-42a6-9abc-dc00d52cfc47)
![image](https://github.com/dqzg12300/fridaUiTools/assets/92798047/25843047-f3e9-4881-baa8-2a8354d389c8)
`Traceback (most recent call last):
  File "kmainForm.py", line 1234, in antiFrida
  File "utils\CmdUtil.py", line 47, in adbshellCmd
  File "utils\CmdUtil.py", line 17, in exec
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 42: invalid start byte`

**Comment by dqzg12300** [comment]
感觉是编码问题。应该切换成utf-8编码运行

**Comment by CHINA-china** [comment]
我将cmd改为utf-8仍然不行，还是会闪退
![image](https://github.com/dqzg12300/fridaUiTools/assets/92798047/8ec1d7c0-51a0-4ab0-b335-4c91f7c487ec)
